config/routes.rb
Rails.application.routes.draw do
  resources :prayers
  resources :users
  resources :prayer_requests

  root 'prayer_requests#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/prayer_request.rb
class PrayerRequest < ActiveRecord::Base
  validates_presence_of :user
  belongs_to :user
  has_many :prayers 
end

app/controllers/prayer_requests_controller.rb
class PrayerRequestsController < ApplicationController
  before_action :set_prayer_request, only: [:show, :edit, :update, :destroy]

  # GET /prayer_requests
  # GET /prayer_requests.json
  def index
    @prayer_requests = PrayerRequest.all
  end

  # GET /prayer_requests/1
  # GET /prayer_requests/1.json
  def show
  end

  # GET /prayer_requests/new
  def new
    @prayer_request = PrayerRequest.new
  end

  # GET /prayer_requests/1/edit
  def edit
  end

  # POST /prayer_requests
  # POST /prayer_requests.json
  def create
    @prayer_request = PrayerRequest.new(prayer_request_params)

    respond_to do |format|
      if @prayer_request.save
        format.html { redirect_to @prayer_request, notice: 'Prayer request was successfully created.' }
        format.json { render :show, status: :created, location: @prayer_request }
      else
        format.html { render :new }
        format.json { render json: @prayer_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prayer_requests/1
  # PATCH/PUT /prayer_requests/1.json
  def update
    respond_to do |format|
      if @prayer_request.update(prayer_request_params)
        format.html { redirect_to @prayer_request, notice: 'Prayer request was successfully updated.' }
        format.json { render :show, status: :ok, location: @prayer_request }
      else
        format.html { render :edit }
        format.json { render json: @prayer_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prayer_requests/1
  # DELETE /prayer_requests/1.json
  def destroy
    @prayer_request.destroy
    respond_to do |format|
      format.html { redirect_to prayer_requests_url, notice: 'Prayer request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prayer_request
      @prayer_request = PrayerRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prayer_request_params
      params.require(:prayer_request).permit(:title, :description, :user_id)
    end
end

app/helpers/prayer_requests_helper.rb
module PrayerRequestsHelper
end

app/views/prayer_requests/_form.html.erb
<%= form_for @prayer_request, :html => { :class => "form-horizontal prayer_request" } do |f| %>

    <% if @prayer_request.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@prayer_request.errors.count, "error") %> prohibited this prayer_request from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @prayer_request.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@prayer_request[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@prayer_request[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :user_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_id, :class => 'form-control' %>
    </div>
    <%= error_span(@prayer_request[:user_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            prayer_requests_path, :class => 'btn btn-default' %>

<% end %>

app/views/prayer_requests/edit.html.erb
<%- model_class = PrayerRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/prayer_requests/index.html.erb
<%- model_class = PrayerRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @prayer_requests.each do |prayer_request| %>
      <tr>
        <td><%= link_to prayer_request.id, prayer_request_path(prayer_request) %></td>
        <td><%= prayer_request.title %></td>
        <td><%= prayer_request.description %></td>
        <td><%= prayer_request.user_id %></td>
        <td><%=l prayer_request.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_prayer_request_path(prayer_request), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      prayer_request_path(prayer_request),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_prayer_request_path,
            :class => 'btn btn-primary' %>

app/views/prayer_requests/new.html.erb
<%- model_class = PrayerRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/prayer_requests/show.html.erb
<%- model_class = PrayerRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @prayer_request.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @prayer_request.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @prayer_request.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              prayer_requests_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_prayer_request_path(@prayer_request), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              prayer_request_path(@prayer_request),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>