config/routes.rb
Rails.application.routes.draw do
  resources :prayers
  resources :users
  resources :prayer_requests

  root 'prayer_requests#index'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/prayer.rb
class Prayer < ActiveRecord::Base
  belongs_to :user
  belongs_to :prayer_request
end

app/controllers/prayers_controller.rb
class PrayersController < ApplicationController
  before_action :set_prayer, only: [:show, :edit, :update, :destroy]

  # GET /prayers
  # GET /prayers.json
  def index
    @prayers = Prayer.all
  end

  # GET /prayers/1
  # GET /prayers/1.json
  def show
  end

  # GET /prayers/new
  def new
    @prayer = Prayer.new
  end

  # GET /prayers/1/edit
  def edit
  end

  # POST /prayers
  # POST /prayers.json
  def create
    @prayer = Prayer.new(prayer_params)

    respond_to do |format|
      if @prayer.save
        format.html { redirect_to @prayer, notice: 'Prayer was successfully created.' }
        format.json { render :show, status: :created, location: @prayer }
      else
        format.html { render :new }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prayers/1
  # PATCH/PUT /prayers/1.json
  def update
    respond_to do |format|
      if @prayer.update(prayer_params)
        format.html { redirect_to @prayer, notice: 'Prayer was successfully updated.' }
        format.json { render :show, status: :ok, location: @prayer }
      else
        format.html { render :edit }
        format.json { render json: @prayer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prayers/1
  # DELETE /prayers/1.json
  def destroy
    @prayer.destroy
    respond_to do |format|
      format.html { redirect_to prayers_url, notice: 'Prayer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prayer
      @prayer = Prayer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prayer_params
      params[:prayer]
    end
end

app/helpers/prayers_helper.rb
module PrayersHelper
end

app/views/prayers/_form.html.erb
<%= form_for(@prayer) do |f| %>
  <% if @prayer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prayer.errors.count, "error") %> prohibited this prayer from being saved:</h2>

      <ul>
      <% @prayer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prayers/edit.html.erb
<h1>Editing Prayer</h1>

<%= render 'form' %>

<%= link_to 'Show', @prayer %> |
<%= link_to 'Back', prayers_path %>

app/views/prayers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prayers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prayers.each do |prayer| %>
      <tr>
        <td><%= link_to 'Show', prayer %></td>
        <td><%= link_to 'Edit', edit_prayer_path(prayer) %></td>
        <td><%= link_to 'Destroy', prayer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prayer', new_prayer_path %>

app/views/prayers/new.html.erb
<h1>New Prayer</h1>

<%= render 'form' %>

<%= link_to 'Back', prayers_path %>

app/views/prayers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_prayer_path(@prayer) %> |
<%= link_to 'Back', prayers_path %>